//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_managemnet_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int roomID { get; set; }
        public string roomNumber { get; set; }
        public string roomType { get; set; }
        public Nullable<decimal> price { get; set; }
        public string roomStatus { get; set; }
        public string roomDescription { get; set; }
        public string roomImage { get; set; }
    }
}
